module.exports = [
  { id: "p1", name: "Aashirvaad Atta", category: "atta", unit: "5 kg", price: 245, mrp: 275, emoji: "🌾", tag: "Bestseller" },
  { id: "p2", name: "Aashirvaad Atta", category: "atta", unit: "10 kg", price: 475, mrp: 530, emoji: "🌾", tag: "" },
  { id: "p3", name: "Fortune Chakki Atta", category: "atta", unit: "5 kg", price: 235, mrp: 260, emoji: "🌾", tag: "" },
  { id: "p4", name: "Maida", category: "atta", unit: "1 kg", price: 48, mrp: 55, emoji: "🍚", tag: "" },
  { id: "p5", name: "Besan", category: "atta", unit: "1 kg", price: 92, mrp: 110, emoji: "🟡", tag: "" },
  { id: "p6", name: "Suji / Rava", category: "atta", unit: "1 kg", price: 52, mrp: 60, emoji: "⚪", tag: "" },
  { id: "p7", name: "India Gate Mini Mogra", category: "rice", unit: "5 kg", price: 310, mrp: 360, emoji: "🍚", tag: "" },
  { id: "p8", name: "Basmati Rice", category: "rice", unit: "1 kg", price: 145, mrp: 170, emoji: "🍚", tag: "" },
  { id: "p9", name: "Sona Masoori Rice", category: "rice", unit: "5 kg", price: 295, mrp: 330, emoji: "🍚", tag: "Value" },
  { id: "p10", name: "Poha", category: "rice", unit: "500 g", price: 42, mrp: 50, emoji: "🥣", tag: "" },
  { id: "p11", name: "Daliya", category: "rice", unit: "500 g", price: 38, mrp: 45, emoji: "🥣", tag: "" },
  { id: "p12", name: "Toor / Arhar Dal", category: "dal", unit: "1 kg", price: 165, mrp: 185, emoji: "🟡", tag: "" },
  { id: "p13", name: "Moong Dhuli", category: "dal", unit: "1 kg", price: 155, mrp: 175, emoji: "🟢", tag: "" },
  { id: "p14", name: "Chana Dal", category: "dal", unit: "1 kg", price: 98, mrp: 115, emoji: "🟡", tag: "" },
  { id: "p15", name: "Masoor Dal", category: "dal", unit: "1 kg", price: 112, mrp: 130, emoji: "🔴", tag: "" },
  { id: "p16", name: "Urad Dal", category: "dal", unit: "1 kg", price: 148, mrp: 165, emoji: "⚫️", tag: "" },
  { id: "p17", name: "Rajma", category: "dal", unit: "1 kg", price: 168, mrp: 190, emoji: "🫘", tag: "" },
  { id: "p18", name: "Chole / Kabuli Chana", category: "dal", unit: "1 kg", price: 125, mrp: 140, emoji: "🟤", tag: "" },
  { id: "p19", name: "Fortune Kachi Ghani Mustard Oil", category: "oil", unit: "1 L", price: 165, mrp: 185, emoji: "🫙", tag: "Bestseller" },
  { id: "p20", name: "Fortune Sunflower Oil", category: "oil", unit: "1 L", price: 138, mrp: 155, emoji: "🌻", tag: "" },
  { id: "p21", name: "Amul Cow Ghee", category: "oil", unit: "500 ml", price: 325, mrp: 355, emoji: "🧈", tag: "" },
  { id: "p22", name: "Desi Ghee", category: "oil", unit: "500 ml", price: 310, mrp: 340, emoji: "🧈", tag: "" },
  { id: "p23", name: "Tata Salt", category: "spices", unit: "1 kg", price: 28, mrp: 32, emoji: "🧂", tag: "" },
  { id: "p24", name: "Haldi Powder", category: "spices", unit: "200 g", price: 62, mrp: 75, emoji: "🟡", tag: "" },
  { id: "p25", name: "Lal Mirch Powder", category: "spices", unit: "200 g", price: 78, mrp: 95, emoji: "🌶️", tag: "" },
  { id: "p26", name: "Dhania Powder", category: "spices", unit: "200 g", price: 55, mrp: 68, emoji: "🌿", tag: "" },
  { id: "p27", name: "Jeera", category: "spices", unit: "100 g", price: 48, mrp: 60, emoji: "🌰", tag: "" },
  { id: "p28", name: "Garam Masala", category: "spices", unit: "100 g", price: 72, mrp: 85, emoji: "✨", tag: "" },
  { id: "p29", name: "MDH Kitchen King", category: "spices", unit: "100 g", price: 82, mrp: 95, emoji: "🍛", tag: "" },
  { id: "p30", name: "Hing", category: "spices", unit: "50 g", price: 58, mrp: 70, emoji: "🫙", tag: "" },
  { id: "p31", name: "Amul Taaza Milk", category: "dairy", unit: "1 L", price: 58, mrp: 62, emoji: "🥛", tag: "" },
  { id: "p32", name: "Amul Butter", category: "dairy", unit: "100 g", price: 58, mrp: 62, emoji: "🧈", tag: "" },
  { id: "p33", name: "Paneer", category: "dairy", unit: "200 g", price: 95, mrp: 110, emoji: "🧀", tag: "" },
  { id: "p34", name: "Dahi / Curd", category: "dairy", unit: "400 g", price: 45, mrp: 50, emoji: "🥛", tag: "" },
  { id: "p35", name: "Maggi 2-Minute Noodles", category: "snacks", unit: "4 pack", price: 56, mrp: 60, emoji: "🍜", tag: "Bestseller" },
  { id: "p36", name: "Parle-G", category: "snacks", unit: "800 g", price: 70, mrp: 80, emoji: "🍪", tag: "" },
  { id: "p37", name: "Good Day Butter Cookies", category: "snacks", unit: "200 g", price: 40, mrp: 45, emoji: "🍪", tag: "" },
  { id: "p38", name: "Haldiram Aloo Bhujia", category: "snacks", unit: "200 g", price: 55, mrp: 62, emoji: "🥨", tag: "" },
  { id: "p39", name: "Lays Classic Salted", category: "snacks", unit: "52 g", price: 20, mrp: 20, emoji: "🥔", tag: "" },
  { id: "p40", name: "Kurkure Masala Munch", category: "snacks", unit: "75 g", price: 20, mrp: 20, emoji: "🌽", tag: "" },
  { id: "p41", name: "Tata Tea Gold", category: "drinks", unit: "250 g", price: 145, mrp: 165, emoji: "☕", tag: "" },
  { id: "p42", name: "Red Label Tea", category: "drinks", unit: "250 g", price: 125, mrp: 140, emoji: "🍵", tag: "" },
  { id: "p43", name: "Nescafe Classic", category: "drinks", unit: "50 g", price: 165, mrp: 185, emoji: "☕", tag: "" },
  { id: "p44", name: "Sugar", category: "drinks", unit: "1 kg", price: 48, mrp: 52, emoji: "🧊", tag: "" },
  { id: "p45", name: "Coca-Cola", category: "drinks", unit: "750 ml", price: 40, mrp: 40, emoji: "🥤", tag: "" },
  { id: "p46", name: "Bisleri Water", category: "drinks", unit: "1 L", price: 20, mrp: 20, emoji: "💧", tag: "" },
  { id: "p47", name: "Lifebuoy Soap", category: "personal", unit: "125 g x 4", price: 96, mrp: 120, emoji: "🧼", tag: "" },
  { id: "p48", name: "Dove Soap", category: "personal", unit: "100 g x 3", price: 135, mrp: 160, emoji: "🧴", tag: "" },
  { id: "p49", name: "Colgate MaxFresh", category: "personal", unit: "150 g", price: 98, mrp: 115, emoji: "😁", tag: "" },
  { id: "p50", name: "Clinic Plus Shampoo", category: "personal", unit: "175 ml", price: 92, mrp: 110, emoji: "💇", tag: "" },
  { id: "p51", name: "Dettol Handwash", category: "personal", unit: "200 ml", price: 85, mrp: 99, emoji: "🧴", tag: "" },
  { id: "p52", name: "Surf Excel Easy Wash", category: "home", unit: "1 kg", price: 128, mrp: 148, emoji: "🧺", tag: "" },
  { id: "p53", name: "Rin Detergent Bar", category: "home", unit: "250 g x 4", price: 52, mrp: 60, emoji: "🟦", tag: "" },
  { id: "p54", name: "Vim Dishwash Bar", category: "home", unit: "200 g x 3", price: 45, mrp: 54, emoji: "🍽️", tag: "" },
  { id: "p55", name: "Lizol Floor Cleaner", category: "home", unit: "500 ml", price: 98, mrp: 115, emoji: "✨", tag: "" },
  { id: "p56", name: "Matchbox / Agarbatti Combo", category: "home", unit: "1 pack", price: 25, mrp: 30, emoji: "🕯️", tag: "" },
];
